Applied Python

In [5]:
! pip install numpy


In [2]:
import numpy as np

In [27]:
import numpy as np
# slicing a 3D array
arr = np.arange(24).reshape(2, 4, 3)
# print(arr)
# print(arr[0::,::3,::2])  # slicing the array
print(arr[::-1,-2::-2,-1::-2])


[[[20 18]
  [14 12]]

 [[ 8  6]
  [ 2  0]]]


In [2]:
# All scalar operations on 1D array using operators
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(a + b)  # addition
print(a - b)  # subtraction
print(a * b)  # multiplication
print(a / b)  # division
print(a ** 2)  # exponentiation
print(a % 2)  # modulus
print(a // 2)  # floor division
print(a > 2)  # greater than
print(a < 2)  # less than
print(a >= 2)  # greater than or equal to
print(a <= 2)  # less than or equal to
print(a == 2)  # equal to
print(a != 2)  # not equal to
print(a & b)  # bitwise AND
print(a | b)  # bitwise OR
print(a ^ b)  # bitwise XOR
print(~a)  # bitwise NOT
print(np.logical_and(a > 2, b < 9))  # logical AND
print(np.logical_or(a > 2, b < 9))  # logical OR
print(np.logical_not(a > 2))  # logical NOT
print(np.logical_xor(a > 2, b < 9))  # logical XOR


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 1  4  9 16 25]
[1 0 1 0 1]
[0 1 1 2 2]
[False False  True  True  True]
[ True False False False False]
[False  True  True  True  True]
[ True  True False False False]
[False  True False False False]
[ True False  True  True  True]
[0 2 0 0 0]
[ 7  7 11 13 15]
[ 7  5 11 13 15]
[-2 -3 -4 -5 -6]
[False False  True False False]
[ True  True  True  True  True]
[ True  True False False False]
[ True  True False  True  True]


DotProduct

In [3]:
# Dot product of two 1D arrays
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.dot(arr1, arr2)  # using numpy dot function

np.int64(32)

In [8]:
# Dot product of two 2D arrays
# a1 = np.array([[1, 2], [3, 4]])
# a2 = np.array([[5, 6], [7, 8]])
a3 = np.arange(12).reshape(3, 4)
a4 = np.arange(12).reshape(4, 3)
print(a3, a4)
# np.dot(a1, a2)  # using numpy dot function

np.dot(a3, a4)  # using numpy dot function

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [ ]:
# Mean of a 1D array
np.mean(a3)

np.float64(5.5)

In [ ]:
# mean of individual columns
np.mean(a3, axis=0)  # mean along the first axis

array([4., 5., 6., 7.])

In [ ]:
# mean of individual rows
np.mean(a3, axis=1)  # mean along the second axis

In [ ]:
np.min(a3)  # minimum value in the array

np.int64(11)

In [16]:
np.max(a3)  # maximum value in the array

np.int64(11)

In [17]:
np.min(a3,axis=0)  # minimum value along the first axis

array([0, 1, 2, 3])

In [18]:
np.max(a3,axis=0)  # maximum value along the first axis

array([ 8,  9, 10, 11])

In [19]:
np.var(a3)  # variance of the array

np.float64(11.916666666666666)

In [24]:
np.var(a3,axis=0) # variance along the first axis

array([10.66666667, 10.66666667, 10.66666667, 10.66666667])

In [23]:
np.var(a3,axis=1) # variance along the second axis

array([1.25, 1.25, 1.25])

In [20]:
np.sum(a3)  # sum of the array

np.int64(66)

In [22]:
np.sum(a3,axis=0)  # sum along the first axis

array([12, 15, 18, 21])

In [21]:
np.sum(a3,axis =0)  # sum of the array

array([12, 15, 18, 21])

In [29]:
# Percentile of a 1D array(percentile is a measure used in statistics indicating the value below which a given percentage falls)
# Percentile is a relative quantity
p25 = np.percentile(a3, 25)  # 25th percentile
p50 = np.percentile(a3, 50)  # 50th percentile (median)
p75 = np.percentile(a3, 75)  # 75th percentile
p90 = np.percentile(a3, 90)  # 90th percentile
p100 = np.percentile(a3, 100)  # 100th percentile (max value)
print("25th percentile:" ,p25)
print("50th percentile (median):", p50)
print("75th percentile:", p75)
print("90th percentile:", p90)
print("100th percentile (max value):", p100)

25th percentile: 2.75
50th percentile (median): 5.5
75th percentile: 8.25
90th percentile: 9.9
100th percentile (max value): 11.0


2D Array

In [ ]:
# 2d array
a2 = np.arange(20).reshape(4, 5)  # creating a 2D array
print(a2)
print()
for i in a2:
    print(i)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [50]:
# add 5 to each element of the 1st row of the 1st matrix
a2 = np.arange(20).reshape(4, 5)
cnt = 5
for i in range(len(a2)):
    a2[i] += cnt  # adding 5 to each element of the row
    cnt += 5  # incrementing the count by 5 for each row
print(a2)



[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


Stacking of numpy array

In [57]:
a = np.arange(12).reshape(3, 4)  # creating a 2D array
b = np.arange(12,24).reshape(3, 4)  # creating another 2D array
print(a)
print()
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [58]:
# Horizontal stacking of two 2D arrays
s = np.hstack((a, b))  # horizontal stacking
print(s)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [ ]:
# Vertical stacking of two 2D arrays
s1 = np.vstack((a, b))  # horizontal stacking
print(s1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# Horizontal splitting of two 2D arrays
s2 = np.hsplit(s, 2)  # horizontal splitting
print(s2)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]
